// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB03HibvbQ6O5hmWkN4kEZNTfQcCSz6DY8',
    appId: '1:656639392887:web:YOUR_WEB_APP_ID',
    messagingSenderId: '656639392887',
    projectId: 'poke-guess-head-to-head-2c305',
    authDomain: 'poke-guess-head-to-head-2c305.firebaseapp.com',
    databaseURL:
        'https://poke-guess-head-to-head-2c305-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'poke-guess-head-to-head-2c305.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB03HibvbQ6O5hmWkN4kEZNTfQcCSz6DY8',
    appId: '1:656639392887:android:bfe6d366f8fa566b0e9a72',
    messagingSenderId: '656639392887',
    projectId: 'poke-guess-head-to-head-2c305',
    databaseURL:
        'https://poke-guess-head-to-head-2c305-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'poke-guess-head-to-head-2c305.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjRmIBnXb9Sf8Rl9Vpv7GG0qGO2vrKrcQ',
    appId: '1:656639392887:ios:bfc047349fac3d740e9a72',
    messagingSenderId: '656639392887',
    projectId: 'poke-guess-head-to-head-2c305',
    databaseURL:
        'https://poke-guess-head-to-head-2c305-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'poke-guess-head-to-head-2c305.firebasestorage.app',
    iosBundleId: 'com.frontendben.pokeGuessHead2Head',
  );
}
